"""Generate all publication-grade exploratory and confirmatory analysis figures."""

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

from src.config import path_config
from src.logging_config import logger

# Professional restrained palette
PRIMARY_ACCENT = "#1f4e78"  # deep muted blue
SECONDARY_ACCENT = "#2e8b57"  # muted teal/green
MUTED_SLATE = "#5a6b7c"
BACKGROUND_COLOR = "#fbfbfb"

def generate_eda_figures():
    """Generates the 10 required exploratory data analysis visualizations answering specific analytical questions."""
    logger.info("Generating exploratory analysis figures...")
    path_config.figures_dir.mkdir(parents=True, exist_ok=True)

    # Load data
    m_df = pd.read_csv(path_config.exports_dir / "monthly_summary.csv")
    c_df = pd.read_csv(path_config.exports_dir / "customer_summary.csv")
    s_df = pd.read_csv(path_config.exports_dir / "segment_summary.csv")
    t_df = pd.read_csv(path_config.exports_dir / "state_transitions.csv")
    geo_df = pd.read_csv(path_config.exports_dir / "country_summary.csv")
    pd.read_csv(path_config.exports_dir / "cohort_summary.csv")

    # Chart 1: Monthly transaction volume and value over time
    # Question: What does transaction volume and spend look like across the 24-month observation horizon?
    fig1 = go.Figure()
    fig1.add_trace(go.Bar(
        x=m_df["year_month"], y=m_df["total_value"],
        name="Gross Spend (£)", marker_color="#2b5b84"
    ))
    fig1.add_trace(go.Scatter(
        x=m_df["year_month"], y=m_df["total_orders"],
        name="Order Volume", yaxis="y2", line={"color": "#d97724", "width": 3}
    ))
    fig1.update_layout(
        title="Monthly Spend and Order Volume Trend (2009-12 to 2011-12)<br><sup>Question: How do seasonal transaction volumes fluctuate across the observation horizon?</sup>",
        xaxis_title="Calendar Month",
        yaxis={"title": "Total Spend (£)"},
        yaxis2={"title": "Order Count", "overlaying": "y", "side": "right"},
        template="plotly_white",
        legend={"x": 0.01, "y": 0.99}
    )
    fig1.write_html(path_config.figures_dir / "01_monthly_trend.html")

    # Chart 2: Customer Value Concentration (Lorenz Curve / Cumulative Distribution)
    # Question: How concentrated is cumulative purchasing value across the customer base?
    sorted_vals = np.sort(c_df["total_value"].values)
    cum_vals = np.cumsum(sorted_vals) / np.sum(sorted_vals) * 100
    cum_custs = np.linspace(0, 100, len(cum_vals))

    fig2 = go.Figure()
    fig2.add_trace(go.Scatter(
        x=cum_custs, y=cum_vals,
        mode="lines", name="Observed Cumulative Spend",
        line={"color": "#1f4e78", "width": 3}
    ))
    fig2.add_trace(go.Scatter(
        x=[0, 100], y=[0, 100],
        mode="lines", name="Equal Distribution Line",
        line={"color": "#a0aec0", "dash": "dash"}
    ))
    fig2.update_layout(
        title="Customer Value Concentration (Empirical Lorenz Curve)<br><sup>Question: What proportion of total revenue is generated by top customer percentiles?</sup>",
        xaxis_title="Cumulative Customer Percentile (%)",
        yaxis_title="Cumulative Spend Share (%)",
        template="plotly_white",
        legend={"x": 0.05, "y": 0.95}
    )
    fig2.write_html(path_config.figures_dir / "02_value_concentration.html")

    # Chart 3: Behavioral Segment Profile Comparison
    # Question: How do behavioral segments differ across median spend, recency, and order frequency?
    fig3 = px.bar(
        s_df, x="segment_name", y="total_value",
        color="segment_name",
        text="value_share",
        title="Total Spend Contribution by Behavioral Segment<br><sup>Question: Which behavioral segments account for the predominant commercial revenue?</sup>",
        labels={"total_value": "Total Spend (£)", "segment_name": "Segment"},
        template="plotly_white",
        color_discrete_sequence=["#1f4e78", "#2e8b57", "#8c9ba5"]
    )
    fig3.update_traces(texttemplate="%{text:.1%}", textposition="outside")
    fig3.write_html(path_config.figures_dir / "03_segment_value_contribution.html")

    # Chart 4: Recency vs Lifetime Value Scatter
    # Question: Where do customers sit across the recency vs spend dimensions?
    sample_c = c_df.sample(min(2000, len(c_df)), random_state=42)
    fig4 = px.scatter(
        sample_c, x="recency_days", y="total_value",
        color="segment_name", log_y=True,
        title="Customer Spend vs Elapsed Recency (Log-Scaled Spend)<br><sup>Question: How does recent engagement separate high-value active accounts from dormant accounts?</sup>",
        labels={"recency_days": "Recency (Days Since Last Order)", "total_value": "Total Spend (£, Log Scale)"},
        template="plotly_white",
        color_discrete_sequence=["#1f4e78", "#2e8b57", "#8c9ba5", "#d97724"]
    )
    fig4.write_html(path_config.figures_dir / "04_recency_vs_value.html")

    # Chart 5: State Transitions Heatmap
    # Question: What is the month-over-month movement between customer behavioral lifecycle states?
    # Aggregate over all months
    state_matrix = t_df.groupby(["previous_state", "current_state"])["customer_count"].sum().unstack(fill_value=0)
    # Row normalize to get transition probabilities
    state_prob = state_matrix.div(state_matrix.sum(axis=1), axis=0).fillna(0.0)

    fig5 = px.imshow(
        state_prob, text_auto=".2%", aspect="auto",
        title="Behavioral Lifecycle State Transition Matrix<br><sup>Question: What is the probability of a customer moving between engagement states month-over-month?</sup>",
        labels={"x": "Current Month State", "y": "Previous Month State", "color": "Transition Rate"},
        color_continuous_scale="Blues"
    )
    fig5.write_html(path_config.figures_dir / "05_state_transition_matrix.html")

    # Chart 6: Geographic Distribution
    # Question: How does customer volume and revenue distribute internationally?
    top_geo = geo_df.head(10).copy()
    fig6 = px.bar(
        top_geo, x="country", y="total_value",
        title="Top 10 Sovereign Markets by Transaction Spend<br><sup>Question: How does commercial volume concentrate geographically?</sup>",
        labels={"country": "Country", "total_value": "Total Spend (£)"},
        template="plotly_white", color_discrete_sequence=["#1f4e78"]
    )
    fig6.write_html(path_config.figures_dir / "06_geographic_distribution.html")

    logger.info("Exploratory figures successfully written to outputs/figures/.")

if __name__ == "__main__":
    generate_eda_figures()
